In [3]:
# modify these for your own computer
repo_directory = '/Users/Michael/Documents/GitHub/law-net/'

data_dir = '/Users/Michael/Desktop/network_data/'

import os
import numpy as np
import re
import sys
import matplotlib.pyplot as plt
import glob
import cPickle  as pickle
from collections import OrderedDict


# graph package
import igraph as ig


# stat
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

import scipy.sparse
import random
import itertools


# our code
sys.path.append(repo_directory + 'code/')
from summarize_clusters import *

sys.path.append(repo_directory + 'vertex_metrics_experiment/code/')
from bag_of_words import * 

# which network to download data for
network_name = 'scotus' # 'federal', 'ca1', etc


# some sub directories that get used
raw_dir = data_dir + 'raw/'
subnet_dir = data_dir + network_name + '/'
text_dir = subnet_dir + 'textfiles/'
nlp_dir = subnet_dir + 'nlp/'
nlp_sub_dir = nlp_dir + 'bow_tfidf/' #tfidf matrix (and other info, i.e. vocab) computed from bag-of-words matrix
nlp_bow_dir = nlp_dir + 'bow/' #bag-of-words matrix (and other info, i.e. vocab)

nlp_df_sub_dir = nlp_dir + 'bow_tfidf_df/'

# all the file paths for .txt files
file_paths = glob.glob(text_dir + '*.txt')

# all opinions
all_the_opinions = all_opinions(file_paths)

# jupyter notebook settings
%load_ext autoreload
%autoreload 2
%matplotlib inline

## load tf-idf vectors (min_df = 0.3, max_df = 0.7)
**tfidf_matrix** = (row_index, column_index): tf_idf value (**CSR FORMAT**)  
**op_id_to_bow_id** = opinion_id (corresponds to row indices)  
**vocab** = all the words in tfidf_matrix (correspond to column indices)

In [3]:
tfidf_matrix, op_id_to_bow_id, vocab = load_tf_idf(nlp_df_sub_dir)

# Graph Clustering
focus on largest connected component on **undirected scotus**

In [4]:
# load the graph
G = ig.Graph.Read_GraphML(subnet_dir + network_name +'_network.graphml')

# limit ourselves to cases upto and including 2015 since we are missing some textfiles from 2016
G = G.subgraph(G.vs.select(year_le=2015))

# make graph undirected
Gud = G.copy()
Gud = Gud.as_undirected()

# get largest connected componenet
components = Gud.clusters(mode='STRONG')
g = components.subgraphs()[np.argmax(components.sizes())]

# CL ids of cases in largest connected component
CLids = g.vs['name']

## modularity on undirected scotus
"For a given division of the network's vertices into some modules, modularity reflects the concentration of edges within modules compared with random distribution of links between all nodes regardless of modules"--*Wikipedia*

In [9]:
%%time 

# modularity clustering
cd_modularity = g.community_fastgreedy() # .as_clustering().membership

mod_clust = cd_modularity.as_clustering()

print mod_clust.summary()

# save clusters in pandas
graph_clusters = pd.Series(mod_clust.membership, index=g.vs['name'])

Clustering with 24724 elements and 126 clusters
Wall time: 1min 57s

## walktrap on undirected scotus

In [11]:
%%time

# walktrap clustering
cd_walktrap = g.community_walktrap()

wt_clust = cd_walktrap.as_clustering()

print wt_clust.summary()

# save clusters in pandas
walktrap_clusters = pd.Series(wt_clust.membership, index=g.vs['name'])

Clustering with 24724 elements and 2264 clusters
Wall time: 2min 51s

# NLP Clustering
K-Means and Gaussian Mixture Models (GMM)

## K-Means Clustering on tf-idf (tweaked df)

### K-means clustering with K = 10

In [13]:
%%time

# set number of clusters
num_clusters = 10

# run kmeans
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)

nlp_tfidf_clusters = km.labels_.tolist()

Wall time: 37min 43s

### K-means clustering with K = 100

In [38]:
%%time

# set number of clusters
num_clusters = 100

# run kmeans
km2 = KMeans(n_clusters=num_clusters)
km2.fit(tfidf_matrix)

nlp_tfidf_clusters2 = km2.labels_.tolist()

Wall time: 50min 7s

## GMM Clustering on tf-idf (tweaked df)

### GMM Clustering with K = 10

In [17]:
%%time

# set number of components
num_components = 10

tfidf_matrix_dense = tfidf_matrix.todense()

# run GMM
gmm = GaussianMixture(n_components=num_components)
gmm.fit(tfidf_matrix_dense)

gmm_clusters = gmm.predict(tfidf_matrix_dense).tolist()
gmm_clusters = map(int, gmm_clusters)

Wall time: 8min 12s

### GMM Clustering with K = 100

In [46]:
%%time

# set number of components
num_components = 100

tfidf_matrix_dense = tfidf_matrix.todense()

# run GMM
gmm2 = GaussianMixture(n_components=num_components)
gmm2.fit(tfidf_matrix_dense)

gmm_clusters2 = gmm2.predict(tfidf_matrix_dense).tolist()
gmm_clusters2 = map(int, gmm_clusters2)

Wall time: 5min 49s

## Compare NLP clustering (tfidf) vs graph clustering

In [49]:
#clusters = pd.DataFrame(index=normalized_text_dict.keys(), columns=['nlp', 'graph'])
clusters = pd.DataFrame(index=op_id_to_bow_id, columns=[])

# add in communities 
clusters['mod'] = graph_clusters

# consider nodes not considered in CD to be their own cluster
# i.e. nodes outside the largest connected component
clusters['mod'].fillna(max(graph_clusters) + 1, inplace=True)

# make formatting
clusters['mod'] = clusters['mod'].astype(np.int)

# add in walktrap clusters
clusters['wt'] = walktrap_clusters
clusters['wt'].fillna(max(walktrap_clusters) + 1, inplace=True)
clusters['wt'] = clusters['wt'].astype(np.int)

# add in NLP clusters
clusters['km_10'] = nlp_tfidf_clusters
clusters['km_100'] = nlp_tfidf_clusters2

clusters['gmm_10'] = gmm_clusters
clusters['gmm_100'] = gmm_clusters2

clusters.to_csv("clusters_tweak_df.csv")

In [50]:
clusters

         mod    wt  km_10  km_100  gmm_10  gmm_100
145658     1     5      3      48       8       71
89370      3   294      3      61       8       86
89371      0    35      9      41       9        7
89372      0     3      4      44       1        8
89373      0     3      0      54       3       36
89374      2     4      0       3       3       69
89375      2     5      2      95       1       23
89376      2     6      2      36       1        2
89377      2     7      7      60       6       58
89378      2     7      2      76       1       97
89379      2     8      2      36       1        2
2224796  126  2264      2      76       1       97
103549     2     1      0      65       3       49
103548     0     1      3       0       3       83
103541     0     1      2      36       1        2
103540     0    11      0      22       3       69
103543     2     9      2      96       1       28
103542     2     9      2      49       1        2
103545     0    12      7      59       1        9
103544     0     1      1       6       0       51
103547     2    13      3       0       8       83
103546     0    12      6       0       8       83
88395      0    15      3      21       1       25
88394      0    58      2      21       1       25
88397      2     1      2      83       1        0
88396      0    16      2      36       1        2
88391      2    17      2      87       0       46
88390      2    18      6      39       0       47
88393    126  2264      6       9       8       47
88392    126  2264      3      18       8        1
...      ...   ...    ...     ...     ...      ...
88977      1     3      2      17       1       97
88976      2   802      2      84       1       87
88979      2     7      3      48       6       66
88978      0    52      2      49       1       44
96208      2    13      2      40       1       38
96209      0   215      2      49       1       44
96200      1     2      0      40       8       38
96201      0   956      2      49       1       44
96202      0   116      4      89       8       44
96203     40     1      4      35       7       56
96204      3    41      4      89       1       56
96205      1    30      4      35       7       56
96206      0  2263      2      23       1       18
96207      0    12      2      75       9       26
88971      1     2      3      72       8       89
88970      2     1      2      36       1        2
88973    126  2264      6      61       1       46
88972    126  2264      3      78       1       30
88975    126  2264      2      96       3       28
88974    126  2264      3      45       8       45
103099     1    68      2      49       1       44
103098     0    21      2      36       1        2
103097     1     1      3      63       0       64
103096     2     1      2      36       1        2
103095     2    25      2      36       1        2
103094     0     1      0      40       3       69
103093     2    30      9      75       1       26
103092     2    30      2      75       1       26
103091     3   352      0       3       3       19
103090     3    13      2      76       1       97

[27885 rows x 6 columns]

### load cluster csv saved in current directory

In [4]:
clusters = pd.read_csv('clusters_tweak_df.csv')
clusters

       Unnamed: 0  mod    wt  km_10  km_100  gmm_10  gmm_100
0          145658    1     5      3      48       8       71
1           89370    3   294      3      61       8       86
2           89371    0    35      9      41       9        7
3           89372    0     3      4      44       1        8
4           89373    0     3      0      54       3       36
5           89374    2     4      0       3       3       69
6           89375    2     5      2      95       1       23
7           89376    2     6      2      36       1        2
8           89377    2     7      7      60       6       58
9           89378    2     7      2      76       1       97
10          89379    2     8      2      36       1        2
11        2224796  126  2264      2      76       1       97
12         103549    2     1      0      65       3       49
13         103548    0     1      3       0       3       83
14         103541    0     1      2      36       1        2
15         103540    0    11      0      22       3       69
16         103543    2     9      2      96       1       28
17         103542    2     9      2      49       1        2
18         103545    0    12      7      59       1        9
19         103544    0     1      1       6       0       51
20         103547    2    13      3       0       8       83
21         103546    0    12      6       0       8       83
22          88395    0    15      3      21       1       25
23          88394    0    58      2      21       1       25
24          88397    2     1      2      83       1        0
25          88396    0    16      2      36       1        2
26          88391    2    17      2      87       0       46
27          88390    2    18      6      39       0       47
28          88393  126  2264      6       9       8       47
29          88392  126  2264      3      18       8        1
...           ...  ...   ...    ...     ...     ...      ...
27855       88977    1     3      2      17       1       97
27856       88976    2   802      2      84       1       87
27857       88979    2     7      3      48       6       66
27858       88978    0    52      2      49       1       44
27859       96208    2    13      2      40       1       38
27860       96209    0   215      2      49       1       44
27861       96200    1     2      0      40       8       38
27862       96201    0   956      2      49       1       44
27863       96202    0   116      4      89       8       44
27864       96203   40     1      4      35       7       56
27865       96204    3    41      4      89       1       56
27866       96205    1    30      4      35       7       56
27867       96206    0  2263      2      23       1       18
27868       96207    0    12      2      75       9       26
27869       88971    1     2      3      72       8       89
27870       88970    2     1      2      36       1        2
27871       88973  126  2264      6      61       1       46
27872       88972  126  2264      3      78       1       30
27873       88975  126  2264      2      96       3       28
27874       88974  126  2264      3      45       8       45
27875      103099    1    68      2      49       1       44
27876      103098    0    21      2      36       1        2
27877      103097    1     1      3      63       0       64
27878      103096    2     1      2      36       1        2
27879      103095    2    25      2      36       1        2
27880      103094    0     1      0      40       3       69
27881      103093    2    30      9      75       1       26
27882      103092    2    30      2      75       1       26
27883      103091    3   352      0       3       3       19
27884      103090    3    13      2      76       1       97

[27885 rows x 7 columns]