In [1]:
# modify these for your own computer
repo_directory = '/Users/Michael/Documents/GitHub/law-net/'

data_dir = '/Users/Michael/Desktop/network_data/'

import os
import numpy as np
import re
import sys
import matplotlib.pyplot as plt
import glob
import cPickle  as pickle
from collections import OrderedDict


# graph package
import igraph as ig


# stat
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

import scipy.sparse
import random
import itertools


# our code
sys.path.append(repo_directory + 'code/')
from summarize_clusters import *

sys.path.append(repo_directory + 'vertex_metrics_experiment/code/')
from bag_of_words import * 

# which network to download data for
network_name = 'scotus' # 'federal', 'ca1', etc


# some sub directories that get used
raw_dir = data_dir + 'raw/'
subnet_dir = data_dir + network_name + '/'
text_dir = subnet_dir + 'textfiles/'
nlp_dir = subnet_dir + 'nlp/'
nlp_sub_dir = nlp_dir + 'bow_tfidf/' #tfidf matrix (and other info, i.e. vocab) computed from bag-of-words matrix
nlp_bow_dir = nlp_dir + 'bow/' #bag-of-words matrix (and other info, i.e. vocab)
nlp_df_sub_dir = nlp_dir + 'bow_tfidf_df/'

# csv location
csv_dir = "C:/Users/Michael/Documents/GitHub/law-net/csv/"

# all the file paths for .txt files
file_paths = glob.glob(text_dir + '*.txt')

# all opinions
all_the_opinions = all_opinions(file_paths)

# jupyter notebook settings
%load_ext autoreload
%autoreload 2
%matplotlib inline

## load tf-idf vectors
**tfidf_matrix** = (row_index, column_index): tf_idf value (**CSR FORMAT**)  
**op_id_to_bow_id** = opinion_id (corresponds to row indices)  
**vocab** = all the words in tfidf_matrix (correspond to column indices)

In [67]:
tfidf_matrix, op_id_to_bow_id, vocab = load_tf_idf(nlp_sub_dir)

In [68]:
tfidf_matrix

<27885x567570 sparse matrix of type '<type 'numpy.float64'>'
	with 20817470 stored elements in Compressed Sparse Row format>

### access small random subset of tfidf matrix (1000 x 100)

In [69]:
random_row_indices = [ i for i in sorted(random.sample(xrange(27885), 1000)) ]
random_column_indices =  [ i for i in sorted(random.sample(xrange(567570), 100)) ]

tfidf_matrix = tfidf_matrix[random_row_indices, :]
tfidf_matrix = tfidf_matrix[:, random_column_indices]
tfidf_matrix

<1000x100 sparse matrix of type '<type 'numpy.float64'>'
	with 31 stored elements in Compressed Sparse Row format>

### the random opinion id's

In [ ]:
random_op_id = []
for op_id, bow_id in op_id_to_bow_id.iteritems():
    for rr_id in random_row_indices:
        if rr_id == bow_id:
            random_op_id.append(op_id)

# K-Means Clustering on tf-idf (random subset)

### K-means clustering with K = 10

In [56]:
%%time

# set number of clusters
num_clusters = 10

# run kmeans
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)

nlp_tfidf_clusters = km.labels_.tolist()

Wall time: 354 ms

### K-means clustering with K = 100

In [59]:
%%time

# set number of clusters
num_clusters = 100

# run kmeans
km2 = KMeans(n_clusters=num_clusters)
km2.fit(tfidf_matrix)

nlp_tfidf_clusters2 = km2.labels_.tolist()

Wall time: 1.01 s

### K-means clustering with K = 1000

In [60]:
%%time

# set number of clusters
num_clusters = 1000

# run kmeans
km3 = KMeans(n_clusters=num_clusters)
km3.fit(tfidf_matrix)

nlp_tfidf_clusters3 = km3.labels_.tolist()

Wall time: 9.39 s

# Gaussian-Mixture-Model (GMM) Clustering on tf-idf (random subset)

### GMM Clustering with K = 10

In [61]:
%%time

# set number of components
num_components = 10

tfidf_matrix_dense = tfidf_matrix.todense()

# run GMM
gmm = GaussianMixture(n_components=num_components)
gmm.fit(tfidf_matrix_dense)

gmm_clusters = gmm.predict(tfidf_matrix_dense).tolist()
gmm_clusters = map(int, gmm_clusters)

Wall time: 177 ms

### GMM Clustering with K = 100

In [62]:
%%time

# set number of components
num_components = 100

tfidf_matrix_dense = tfidf_matrix.todense()

# run GMM
gmm2 = GaussianMixture(n_components=num_components)
gmm2.fit(tfidf_matrix_dense)

gmm_clusters2 = gmm2.predict(tfidf_matrix_dense).tolist()
gmm_clusters2 = map(int, gmm_clusters2)

Wall time: 2.06 s

### GMM Clustering with K = 1000

In [63]:
%%time

# set number of components
num_components = 1000

tfidf_maatrix_dense = tfidf_matrix.todense()

# run GMM
gmm3 = GaussianMixture(n_components=num_components)
gmm3.fit(tfidf_matrix_dense)

gmm_clusters3 = gmm3.predict(tfidf_matrix_dense).tolist()
gmm_clusters3 = map(int, gmm_clusters3)

Wall time: 29.2 s

## NLP Clustering (K-Means & GMM) on Random Subset

In [73]:
#clusters = pd.DataFrame(index=normalized_text_dict.keys(), columns=['nlp', 'graph'])
clusters = pd.DataFrame(index=random_op_id, columns=[])

# add in NLP clusters
clusters['km_10'] = nlp_tfidf_clusters
clusters['km_100'] = nlp_tfidf_clusters2
clusters['km_1000'] = nlp_tfidf_clusters3

clusters['gmm_10'] = gmm_clusters
clusters['gmm_100'] = gmm_clusters2
clusters['gmm_1000'] = gmm_clusters3

clusters.to_csv(csv_dir + "clusters_random_subset.csv")

In [74]:
clusters

         km_10  km_100  km_1000  gmm_10  gmm_100  gmm_1000
89375        0       0        0       0        0         4
97159        0       0        0       0        0         4
88022        0       0        0       0        0         4
100010       0       0        0       0        0         4
94541        0       0        0       0        0         4
97935        0       0        0       0        0         4
109857       0       0        0       0        0         4
103709       0       0        0       0        0         4
92749        0       0        0       0        0         4
85677        0       0        0       0        0         4
87299        0       0        0       0        0         4
89494        0       0        0       0        0         4
90872        0       0        0       0        0         4
90121        0       0        0       0        0         4
90126        9      71       72       4       50        46
95186        0       0        0       0        0         4
91348        0       0        0       0        0         4
110514       0       0        0       0        0         4
112040       0       0        0       0        0         4
99952        0       0        0       0        0         4
105404       0       0        0       0        0         4
102752       0       0        0       0        0         4
102759       0       0        0       0        0         4
109665       0       0        0       0        0         4
111003       0       0        0       0        0         4
111007       0       0        0       0        0         4
88881        0       0        0       0        0         4
112648       0       0        0       0        0         4
104828       0       0        0       0        0         4
107039       0       0        0       0        0         4
...        ...     ...      ...     ...      ...       ...
85809        0       0        0       0        0         4
103789       0       0        0       0        0         4
87988        0       0        0       0        0         4
86059        0       0        0       0        0         4
2442451      0       0        0       0        0         4
101434       0       0        0       0        0         4
110922       0       0        0       0        0         4
97290        0       0        0       0        0         4
99659        0       0        0       0        0         4
109344       0       0        0       0        0         4
111242       0       0        0       0        0         4
107371       0       0        0       0        0         4
101231       0       0        0       0        0         4
85218        0       0        0       0        0         4
103611       0       0        0       0        0         4
85215        0       0        0       0        0         4
105267       0       0        0       0        0         4
108574       0       0        0       0        0         4
88213        0       0        0       0        0         4
101574       0       0        0       0        0         4
101570       0       0        0       0        0         4
87466        0       0        0       0        0         4
98802        0       0        0       0        0         4
86338        0       0        0       0        0         4
2409992      0       0        0       0        0         4
1088002      0       0        0       0        0         4
98477        0       0        0       0        0         4
104078       0       0        0       0        0         4
88978        2      11       31       4       79        79
96204        0       0        0       0        0         4

[1000 rows x 6 columns]

### load cluster csv saved in current directory

In [77]:
clusters = pd.read_csv(csv_dir + 'clusters_random_subset.csv')
clusters

     Unnamed: 0  km_10  km_100  km_1000  gmm_10  gmm_100  gmm_1000
0         89375      0       0        0       0        0         4
1         97159      0       0        0       0        0         4
2         88022      0       0        0       0        0         4
3        100010      0       0        0       0        0         4
4         94541      0       0        0       0        0         4
5         97935      0       0        0       0        0         4
6        109857      0       0        0       0        0         4
7        103709      0       0        0       0        0         4
8         92749      0       0        0       0        0         4
9         85677      0       0        0       0        0         4
10        87299      0       0        0       0        0         4
11        89494      0       0        0       0        0         4
12        90872      0       0        0       0        0         4
13        90121      0       0        0       0        0         4
14        90126      9      71       72       4       50        46
15        95186      0       0        0       0        0         4
16        91348      0       0        0       0        0         4
17       110514      0       0        0       0        0         4
18       112040      0       0        0       0        0         4
19        99952      0       0        0       0        0         4
20       105404      0       0        0       0        0         4
21       102752      0       0        0       0        0         4
22       102759      0       0        0       0        0         4
23       109665      0       0        0       0        0         4
24       111003      0       0        0       0        0         4
25       111007      0       0        0       0        0         4
26        88881      0       0        0       0        0         4
27       112648      0       0        0       0        0         4
28       104828      0       0        0       0        0         4
29       107039      0       0        0       0        0         4
..          ...    ...     ...      ...     ...      ...       ...
970       85809      0       0        0       0        0         4
971      103789      0       0        0       0        0         4
972       87988      0       0        0       0        0         4
973       86059      0       0        0       0        0         4
974     2442451      0       0        0       0        0         4
975      101434      0       0        0       0        0         4
976      110922      0       0        0       0        0         4
977       97290      0       0        0       0        0         4
978       99659      0       0        0       0        0         4
979      109344      0       0        0       0        0         4
980      111242      0       0        0       0        0         4
981      107371      0       0        0       0        0         4
982      101231      0       0        0       0        0         4
983       85218      0       0        0       0        0         4
984      103611      0       0        0       0        0         4
985       85215      0       0        0       0        0         4
986      105267      0       0        0       0        0         4
987      108574      0       0        0       0        0         4
988       88213      0       0        0       0        0         4
989      101574      0       0        0       0        0         4
990      101570      0       0        0       0        0         4
991       87466      0       0        0       0        0         4
992       98802      0       0        0       0        0         4
993       86338      0       0        0       0        0         4
994     2409992      0       0        0       0        0         4
995     1088002      0       0        0       0        0         4
996       98477      0       0        0       0        0         4
997      104078      0       0        0       0        0         4
998       88978      2      11       31       4       79        79
999       96204      0       0        0       0        0         4

[1000 rows x 7 columns]